SELECT IDPREST, PRESTADORA, TIPO, ORDEM, TOTCUSTO, QTD,
    CAST (CASE WHEN TIPO = 2 THEN SUM(TOTCUSTO) ELSE 0 END AS DOUBLE PRECISION) TOTCUSTOGERAL,
    CAST (CASE WHEN TIPO = 2 THEN SUM(QTD) ELSE 0 END AS DOUBLE PRECISION) QTDGERAL
FROM
(
SELECT
   IDPREST,
   PRESTADORA,
   TIPO,
   ORDEM,
   SUM(CAST(TOTCUSTO AS NUMERIC(15,2))) TOTCUSTO,
   SUM(CAST(QTD AS INTEGER))QTD
FROM
(
   SELECT
      P.T210IDPREST IDPREST,
      '  • ' || P.T210NOME PRESTADORA,
      CAST ('01.01.2015' AS DATE) DATAREG,
      0 TOTCUSTO,
      0 QTD,
      0 ORDEM,
      0 TIPO
   FROM T210SPCPRESTADOR P

   UNION

   SELECT
      P.T210IDPREST IDPREST,
      '      - ' || S.T211DESCRICAO PRESTADORA,
      CAST(C.T214DATAHORA AS DATE) DATAREG,
      SUM(C.T214CUSTO) TOTCUSTO,
      CAST(COUNT(*) AS INTEGER) QTD,
      1 ORDEM,
      1 TIPO
   FROM T214SPCCONSULTAS C
   INNER JOIN T211SPCSERVICO S ON C.T214IDSERVICO = S.T211IDSERVICO
   INNER JOIN T210SPCPRESTADOR P ON S.T211IDPREST = P.T210IDPREST
   WHERE CHAR_LENGTH(C.T214PROTOCOLO) > 5
   GROUP BY 1,2,3

   UNION

   SELECT
      P.T210IDPREST IDPREST,
      '      - '||'Negativações' PRESTADORA,
      CAST(L.T218DATAHORARET AS DATE) DATAREG,
      SUM(N.T219CUSTOREG) TOTCUSTO,
      CAST(COUNT(*) AS INTEGER) QTD,
      2 ORDEM,
      1 TIPO
   FROM T218SPCLOTEMOV L
   INNER JOIN T219SPCLOTENEGITENS N ON L.T218IDLOTE = N.T219IDLOTE
   INNER JOIN T210SPCPRESTADOR P ON L.T218PRESTADORA = P.T210IDPREST
   WHERE L.T218TIPOMOV = 'I' AND N.T219CODRETORNO = 0 AND N.T219IDLOTE <> 1
   AND L.T218IDLOTE > 5
   GROUP BY 1,2,3

   UNION

   SELECT
         IDPREST,
         '  • ' ||'TOTAL' PRESTADORA,
         DATAREG,
         (TOTCUSTO),
         (QTD),
         1 ORDEM,
         2 TIPO
   FROM
   (
      SELECT
         P.T210IDPREST IDPREST,
         '  • ' || 'Total' PRESTADORA,
         CAST(C.T214DATAHORA AS DATE) DATAREG,
         SUM(C.T214CUSTO) TOTCUSTO,
         CAST(COUNT(*) AS INTEGER) QTD,
         1 ORDEM,
         2 TIPO
      FROM T214SPCCONSULTAS C
      INNER JOIN T211SPCSERVICO S ON C.T214IDSERVICO = S.T211IDSERVICO
      INNER JOIN T210SPCPRESTADOR P ON S.T211IDPREST = P.T210IDPREST
      WHERE CHAR_LENGTH(C.T214PROTOCOLO) > 5
      GROUP BY 1,2,3
   
   UNION
   
      SELECT
         P.T210IDPREST IDPREST,
         'Negativações' PRESTADORA,
         CAST(L.T218DATAHORARET AS DATE) DATAREG,
         SUM(N.T219CUSTOREG) TOTCUSTO1,
         CAST(COUNT(*) AS INTEGER) QTD,
         2 ORDEM,
         1 TIPO
      FROM T218SPCLOTEMOV L
      INNER JOIN T219SPCLOTENEGITENS N ON L.T218IDLOTE = N.T219IDLOTE
      INNER JOIN T210SPCPRESTADOR P ON L.T218PRESTADORA = P.T210IDPREST
      WHERE L.T218TIPOMOV = 'I' AND N.T219CODRETORNO = 0 AND N.T219IDLOTE <> 1
      AND L.T218IDLOTE > 5
      GROUP BY 1,2,3

   )

) WHERE (DATAREG BETWEEN :INICIO AND :FIM) OR (TIPO = 0)

GROUP BY 1,2,3,4
ORDER BY IDPREST, TIPO, ORDEM)
GROUP BY 1,2,3,4,5,6




Select
TO_CHAR(L.competencia, 'DD/MM/YYYY') COMPETENCIA,
P.Codigo CODPROD, 

cast(
Sum(Case
When L.Natureza = 'D' Then I.ValorTotal - COALESCE(I.DESCONTOSVALOR,0) + COALESCE (I.ACRESCIMOSVALOR,0) + COALESCE (I.FRETE,0)
ELSE 0 --I.ValorTotal * (-1)
END
)
AS float) RECBRUTA

FROM Benner_Corp.Cm_Itens I
INNER JOIN Benner_Corp.Pd_Produtos P On I.Produto = P.Handle
INNER Join Benner_Corp.Ct_Lancamentos L On I.Handle = L.LancamentoFinanceiroItem
INNER Join Benner_Corp.Ct_Contas C On L.Conta = C.Handle

Where 1 = 1
--And L.Competencia = to_date('01/07/2022', 'DD/MM/YYYY')
And L.Competencia = to_date('01/'|| :Mes || '/' || :Ano, 'DD/MM/YYYY')
And L.Conta = 10917 AND C.EMPRESA = 100

Group By L.competencia, P.Codigo
Order by 1, 2