EXECUTE BLOCK
RETURNS (
 IDPRODUTO INTEGER
)
AS
BEGIN
   FOR

   SELECT P.T050IDPROD
   FROM T050PRODUTOS P 
   WHERE P.T050IDPROD IN (
    SELECT S.T053PRODUTO FROM T053SALDOS S 
    WHERE S.T053PRODUTO NOT IN (
        SELECT DISTINCT MV.T094PRODUTO
        FROM T094MOVPROD MV
        WHERE MV.T094DATA > DATEADD(MONTH,-12, CURRENT_DATE)
    ) 
    GROUP BY S.T053PRODUTO
    HAVING SUM(S.T053SALDO) <= 0
    AND SUM(S.T053CONSIGNACAO) <= 0
    AND SUM(S.T053TERCEIROS) <=0
    AND SUM(S.T053EMTRANS) <=0
    AND SUM(S.T053MOSTRUARIO) <=0
   
   ) 
   AND P.T050ATIVO = 'S'
   AND P.T050TIPOPROD = 3 --(MERC REVENDA)

   INTO :IDPRODUTO
    DO
    BEGIN
     --UPDATE T050PRODUTOS PR SET PR.T050ATIVO = 'N' WHERE PR.T050IDPROD = :IDPRODUTO;
     SUSPEND;
    END
END

]

SELECT
   P.T050IDPROD,
   SUM(S.T053SALDO)
   FROM T050PRODUTOS P
   INNER JOIN T053SALDOS S
   ON S.T053PRODUTO = P.T050IDPROD
   INNER JOIN T094MOVPROD MV
   ON  MV.T094PRODUTO = P.T050IDPROD
   --AND MV.T094ESTOQUE = 0
   WHERE P.T050ATIVO = 'S'
   AND P.T050TIPOPROD = 3 --(MERC REVENDA)
   AND MV.T094DATA > DATEADD(MONTH,-12, CURRENT_DATE)
   GROUP BY P.T050IDPROD
   --HAVING SUM(S.T053SALDO) <= 0
   --AND SUM(S.T053CONSIGNACAO) <= 0
   --AND SUM(S.T053TERCEIROS) <=0
   -- SUM(S.T053EMTRANS) <=0

EXECUTE BLOCK
RETURNS (
 IDPRODUTO INTEGER
)

AS
BEGIN
   FOR

WITH MOV AS (
     SELECT DISTINCT MV.T094PRODUTO
     FROM T094MOVPROD MV
     WHERE MV.T094DATA > DATEADD(MONTH,-12, CURRENT_DATE)
),
PRD AS (
    SELECT P.T050IDPROD
    FROM T050PRODUTOS P
    WHERE
    P.T050ATIVO = 'S'
    AND P.T050TIPOPROD = 3 --(MERC REVENDA)
), SLD AS (
   SELECT S.T053PRODUTO FROM T053SALDOS S
   GROUP BY S.T053PRODUTO
   HAVING SUM(S.T053SALDO) <= 0
   AND SUM(S.T053CONSIGNACAO) <= 0
   AND SUM(S.T053TERCEIROS) <=0
   AND SUM(S.T053EMTRANS) <=0
   AND SUM(S.T053MOSTRUARIO) <=0
)
 
 SELECT PRD.T050IDPROD FROM PRD
 INNER JOIN SLD ON SLD.T053PRODUTO = PRD.T050IDPROD
 WHERE PRD.T050IDPROD NOT IN (
  SELECT MOV.T094PRODUTO
  FROM MOV
 )
INTO :IDPRODUTO
    DO
    BEGIN
     UPDATE T050PRODUTOS PR SET PR.T050ATIVO = 'N' WHERE PR.T050IDPROD = :IDPRODUTO;
     SUSPEND;
    END
END










1642

EXECUTE BLOCK
RETURNS (
 IDPRODUTO INTEGER
)
AS

declare variable ULT_HIG VARCHAR(100);
declare VARIABLE DATA_BASE DATE;

BEGIN

SELECT VALOR, DATEADD(MONTH,-12,CURRENT_DATE )
FROM CONFIGURACOES C
WHERE C.PARAMETRO = 'ULT_HIG_PRODUTOS'
INTO :ULT_HIG, :DATA_BASE;


IF (CAST(:ULT_HIG AS DATE) >= :DATA_BASE) THEN BEGIN
    SUSPEND;
    EXIT;
END

FOR
    WITH MOV AS (
         SELECT DISTINCT MV.T094PRODUTO
         FROM T094MOVPROD MV
         WHERE MV.T094DATA > DATEADD(MONTH,-12, CURRENT_DATE)
    ),
    PRD AS (
        SELECT P.T050IDPROD
        FROM T050PRODUTOS P
        WHERE
        P.T050ATIVO = 'S'
        AND P.T050TIPOPROD = 3 --(MERC REVENDA)
    ), SLD AS (
       SELECT S.T053PRODUTO FROM T053SALDOS S
       GROUP BY S.T053PRODUTO
       HAVING SUM(S.T053SALDO) <= 0
       AND SUM(S.T053CONSIGNACAO) <= 0
       AND SUM(S.T053TERCEIROS) <=0
       AND SUM(S.T053EMTRANS) <=0
       AND SUM(S.T053MOSTRUARIO) <=0
    )
     
     SELECT PRD.T050IDPROD FROM PRD
     INNER JOIN SLD ON SLD.T053PRODUTO = PRD.T050IDPROD
     WHERE PRD.T050IDPROD NOT IN (
      SELECT MOV.T094PRODUTO
      FROM MOV
     )
    INTO :IDPRODUTO
        DO
        BEGIN
          UPDATE T050PRODUTOS PR SET PR.T050ATIVO = 'N' WHERE PR.T050IDPROD = :IDPRODUTO;
          UPDATE CONFIGURACOES C SET C.VALOR = CURRENT_DATE;
          SUSPEND;
        END
END






EXECUTE BLOCK
RETURNS (
 IDPRODUTO INTEGER,
 DESCRICAO VARCHAR(120),
 ARTIGO VARCHAR(40),
 ULT_ALTERACAO TIMESTAMP
)
AS

DECLARE VARIABLE ULT_HIG VARCHAR(100);
DECLARE VARIABLE DATA_BASE DATE;

BEGIN

SELECT VALOR, DATEADD(MONTH,-12,CURRENT_DATE )
FROM CONFIGURACOES C
WHERE C.PARAMETRO = 'ULT_HIG_PRODUTOS'
INTO :ULT_HIG, :DATA_BASE;


IF (CAST(:ULT_HIG AS DATE) >= :DATA_BASE OR :ULT_HIG IS NULL ) THEN BEGIN
    SUSPEND;
    EXIT;
END

FOR
    WITH MOV AS (
         SELECT DISTINCT MV.T094PRODUTO
         FROM T094MOVPROD MV
         WHERE MV.T094DATA > DATEADD(MONTH,-12, CURRENT_DATE)
    ),
    PRD AS (
        SELECT P.T050IDPROD, P.T050DESCRICAO,P.T050LASTCHANGE, A.T047DESCRICAO
        FROM T050PRODUTOS P
        INNER JOIN T047ARTIGOS A
        ON A.T047IDARTIGO = P.T050ARTIGO
        WHERE
        P.T050ATIVO = 'S'
        AND P.T050TIPOPROD = 3 --(MERC REVENDA)
    ), SLD AS (
       SELECT * FROM T053SALDOS S
       GROUP BY S.T053PRODUTO
       HAVING SUM(S.T053SALDO) <= 0
       AND SUM(S.T053CONSIGNACAO) <= 0
       AND SUM(S.T053TERCEIROS) <=0
       AND SUM(S.T053EMTRANS) <=0
       AND SUM(S.T053MOSTRUARIO) <=0
    )
     
     SELECT PRD.T050IDPROD, PRD.T050DESCRICAO, PRD.T047DESCRICAO, PRD.T050LASTCHANGE FROM PRD
     INNER JOIN SLD ON SLD.T053PRODUTO = PRD.T050IDPROD
     WHERE PRD.T050IDPROD NOT IN (
      SELECT MOV.T094PRODUTO
      FROM MOV
     )
    INTO :IDPRODUTO, :DESCRICAO, :ARTIGO,:ULT_ALTERACAO
        DO
        BEGIN
          --UPDATE T050PRODUTOS PR SET PR.T050ATIVO = 'N' WHERE PR.T050IDPROD = :IDPRODUTO;
          --UPDATE CONFIGURACOES C SET C.VALOR = CURRENT_DATE WHERE C.PARAMETRO = 'ULT_HIG_PRODUTOS';
          SUSPEND;
        END
END





EXECUTE BLOCK
RETURNS (
 IDPRODUTO INTEGER,
 DESCRICAO VARCHAR(120),
 ARTIGO VARCHAR(40),
 ULT_ALTERACAO TIMESTAMP
)
AS

DECLARE VARIABLE ULT_HIG VARCHAR(100);
DECLARE VARIABLE DATA_BASE DATE;

BEGIN

SELECT VALOR, DATEADD(MONTH,-12,CURRENT_DATE )
FROM CONFIGURACOES C
WHERE C.PARAMETRO = 'ULT_HIG_PRODUTOS'
INTO :ULT_HIG, :DATA_BASE;


--IF (CAST(:ULT_HIG AS DATE) >= :DATA_BASE OR :ULT_HIG IS NULL ) THEN BEGIN
--    SUSPEND;
--    EXIT;
--END

FOR
    WITH MOV AS (
         SELECT DISTINCT MV.T094PRODUTO
         FROM T094MOVPROD MV
         WHERE MV.T094DATA > DATEADD(MONTH,-12, CURRENT_DATE)
    ),
    PRD AS (
        SELECT P.T050IDPROD, P.T050DESCRICAO,P.T050LASTCHANGE, A.T047DESCRICAO
        FROM T050PRODUTOS P
        INNER JOIN T047ARTIGOS A
        ON A.T047IDARTIGO = P.T050ARTIGO
        WHERE
        P.T050ATIVO = 'S'
        AND P.T050TIPOPROD = 3 --(MERC REVENDA)
    ), SLD AS (
       SELECT S.T053PRODUTO FROM T053SALDOS S
       GROUP BY S.T053PRODUTO
       HAVING SUM(S.T053SALDO) <= 0
       AND SUM(S.T053CONSIGNACAO) <= 0
       AND SUM(S.T053TERCEIROS) <=0
       AND SUM(S.T053EMTRANS) <=0
       AND SUM(S.T053MOSTRUARIO) <=0
    )
     
     SELECT PRD.T050IDPROD, PRD.T050DESCRICAO, PRD.T047DESCRICAO, PRD.T050LASTCHANGE FROM PRD
     INNER JOIN SLD ON SLD.T053PRODUTO = PRD.T050IDPROD
     WHERE PRD.T050LASTCHANGE <= DATEADD(MONTH,-12,CURRENT_DATE )
     AND PRD.T050IDPROD NOT IN (
      SELECT MOV.T094PRODUTO
      FROM MOV
     )
    INTO :IDPRODUTO, :DESCRICAO, :ARTIGO,:ULT_ALTERACAO
        DO
        BEGIN
          --UPDATE T050PRODUTOS PR SET PR.T050ATIVO = 'N' WHERE PR.T050IDPROD = :IDPRODUTO;
          --UPDATE CONFIGURACOES C SET C.VALOR = CURRENT_DATE WHERE C.PARAMETRO = 'ULT_HIG_PRODUTOS';
          SUSPEND;
        END
END






